[package]
name = "rspc"
description = "A blazing fast and easy to use tRPC server for Rust."
version = "1.0.0-rc.5"
authors = ["Oscar Beaumont <oscar@otbeaumont.me>"]
edition = "2021"
license = "MIT"
include = ["/src", "/LICENCE", "/README.md"]
repository = "https://github.com/oscartbeaumont/rspc"
documentation = "https://docs.rs/rspc/latest/rspc"
keywords = ["async", "specta", "rust-to-ts", "typescript", "typesafe"]
categories = ["web-programming", "asynchronous"]

# /bin/sh RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc --all-features
[package.metadata."docs.rs"]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = []
tracing = ["dep:tracing"]

[dependencies]
rspc-core = { version = "0.0.1", path = "./crates/core" }
specta = { workspace = true }

serde = { workspace = true }
thiserror = { workspace = true }
futures = { version = "0.3.28", default-features = false, features = ["std", "async-await"] } # TODO: Drop for `futures_core` if possible
pin-project-lite = "0.2.13"


tracing = { version = "0.1.40", default-features = false, optional = true }


# TODO: Remove `serde_json`
serde_json = { version = "1", default-features = false }

[dev-dependencies]
# Tests
async-stream = "0.3.5"
tokio = { version = "1.33.0", features = ["macros", "rt-multi-thread"] }
tauri = { version = "1.5.2", features = ["api-all"] }

[workspace]
members = ["./crates/*", "./examples", "./examples/axum", "./examples/tauri/src-tauri"]


# TODO: Probs remove this
[workspace.dependencies]
specta = { version = "=2.0.0-rc.7", default-features = false, features = ["serde", "serde_json"] }
serde = { version = "1", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.50", default-features = false }
