[package]
name = "rspc"
version = "0.2.0"
edition = "2021"

[dependencies]
# Public
serde = { version = "1", default-features = false }
specta = { version = "1", default-features = false }

# Private
erased-serde = { version = "0.4.2", default-features = false, features = ["std"] }

# Temporary
serde_json = "1"
tokio = "1"
serde-value = "0.7.0"
futures = "0.3.30"
