[package]
name = "rspc-core"
version = "0.0.1"
edition = "2021"
publish = false    # TODO

# /bin/sh RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc --all-features
[package.metadata."docs.rs"]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
# Public API
futures-core = "0.3"
serde = "1"

# Private API
erased-serde = "0.4.1"

# TODO: Remove
serde-value = "0.7.0"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
serde_json = "1"                               # TODO: Remove this
futures = "0.3"
